### ISSUE TITLE
Works incorrectly on empty attributes?

### ISSUE THREAD

**Issue by viperet** [holloway/xml-zero.js#5]
I created a simple test case to show the problem:
String:
`<?xml version=""?><root></root>`
Result:
`    [
      [ 'XML_DECLARATION', 'xml' ],
      [ 'ATTRIBUTE_NODE', 'version', '"?><root></root>' ]
]`

Everything after the version attribute is parsed as attribute value.

**Comment by viperet** [comment]
@holloway created a PR for this issue https://github.com/holloway/xml-zero.js/pull/6

**Comment by holloway** [comment]
Thanks I've merged your PR.

fyi I'm keeping this project in maintenance mode for now as I've started using SAX-WASM instead which is much faster than my library https://github.com/justinwilaby/sax-wasm

**Comment by viperet** [comment]
@holloway thanks for the work on this parser!
FYI it is used in vscode-maven  https://github.com/microsoft/vscode-maven/blob/master/src/utils/lexerUtils.ts  (Visual Studio Code extension) and I was suggested to use it for parsing XML in my VSCode extension too.

**Comment by viperet** [comment]
@holloway please also update https://www.npmjs.com/package/xml-zero-lexer

**Comment by holloway** [comment]
@viperet good to know, thanks, and yes I'll update that NPM package today. Cheers :smile:

**Comment by holloway** [comment]
@viperet https://www.npmjs.com/package/xml-zero-lexer has been published. Thanks for you contrib!
