### ISSUE TITLE
Add missing positions

### ISSUE THREAD

**Issue by loveencounterflow** [holloway/xml-zero.js#7]
Hi there, I'm trying out `xml-zero-lexer` and I realized that doctype tags, but much more importantly all `CLOSE_ELEMENT` tokens lack any positional data. I can sort-of reconstruct part of the missing data by looking at neighboring tokens; however, that fails in the case where you have nothing but a series of closing tags, as in `</p1></p2></p3></p4>`. Granted, that's not a likely XML/HTML document, but OTOH since the lexer must have looked at all the text anyway, couldn't it supply the start and stop positions as well? What's more, depending on use case, one may want to check for tags being properly nested later on, and to do that you need to know the tagname, which is only retrievable with the source and the start/stop positions.

**Comment by holloway** [comment]
> couldn't it supply the start and stop positions as well? 

Yes, it could store them but I was trying to avoid making variables unless I needed them.

That said, I'm happy to add this feature and I'll accept a PR to add this.

> What's more, depending on use case, one may want to check for tags being properly nested later on, 

Makes sense. I think the lexer itself probably shouldn't test for 'well formedness' but I understand that if something using the lexer wanted that info.

**Comment by loveencounterflow** [comment]
I must confess I'd have trouble formulating a pull request. I had a look at the code and I don't think I understand it well enough. As a stopgap measure, I think I will just look for the sequence opening pointy bracket, slash, XML name; I think that's what you're doing.

> the lexer itself probably shouldn't test for 'well formedness'

Exactly. I consider that a feature of the lexer.

**Comment by holloway** [comment]
@loveencounterflow Ping me if no one opens a PR in a month and I'll do it :)

**Comment by loveencounterflow** [comment]
OK. For the sake of completeness, the `<!DOCTYPE ...>` has no associated positions either.

**Comment by holloway** [comment]
@loveencounterflow fyi I've added this now
